### ISSUE TITLE
Error: Please login to use Windscribe

### ISSUE THREAD

**Issue by yelnyafacee** [arm358/windscribe-python-wrapper#1]
Hi, I tried: 
```
vpn = Windscribe('servers.txt', vpn_user, vpn_password)
vpn.connect()

```
but all I get is:

```
Please login to use Windscribe
```
is this broken?:
```
    def login(self, user, password):
    
        print('test: user:' + user + ' password: ' + password)
    
        """logs into Windscribe using provided credentials"""
        commands = ["windscribe", "login"]
        proc = subprocess.Popen(commands, universal_newlines=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        proc.stdin.write(user)
        proc.stdin.write(password)
```
I checked the password and user is correct

I have to manually type with the windscribe CLI to login to make it work:

```
windscribe login
```

**Comment by arm358** [comment]
Syntax is correct -- looks like the newest version of Linux Windscribe broke the behavior. I think they're using "GetPass" now which will not take input from stdin, only from /dev/tty which would be an actual keyboard. Need to rethink how to do this unfortunately.
