### ISSUE TITLE
Code with newest release [v2.7.6] doesn't work.

### ISSUE THREAD

**Issue by MarcelSuleiman** [arm358/windscribe-python-wrapper#4]
Code with newest release [v2.7.6](https://deploy.totallyacdn.com/desktop-apps/2.7.6/windscribe_2.7.6_guinea_pig_amd64.deb) doesn't work.

File "/home/.../.../.../.../windscribe.py", line 16, in login
    proc = subprocess.Popen(commands, universal_newlines=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'windscribe'

**Comment by arm358** [comment]
added your update thanks

**Comment by MarcelSuleiman** [comment]
Oh man :D sorry I deleted forked code from my GH and this action closed my PR, you need add `windscribe-cli` everywhere in code where you have just `windscribe` I made another try to PR... #5
